### ISSUE TITLE
缺少编译依赖 vsp_ioctl.h

### ISSUE THREAD

**Issue by xqbumu** [yodaos-project/yodaos#10]
OpenWrt config: products/rokid/dev3.3/configs/leo_k18_dev33_defconfig

编译 Building C object modules/mic_array/CMakeFiles/mic_array.default.dir/mic_array.c.o 时，缺少 vsp_ioctl.h。
经验证，在 openwrt/build_dir/target-arm_cortex-a7+neon_glibc-2.22_eabi/android-hardware/modules/mic_array/CMakeFiles/mic_array.default.dir/flags.make 中，C_INCLUDES 添加
-I/diskdata1/yodaos/openwrt/build_dir/target-arm_cortex-a7+neon_glibc-2.22_eabi/android-hardware/nationalchip/gx8010/vsp_firmware/include 即可解决。

此为临时解决方案，需要在编译依赖处添加相关配置。 

随后，再次编译，在其它位置也发现该问题。。。

```
In file included from /diskdata1/yodaos/openwrt/build_dir/target-arm_cortex-a7+neon_glibc-2.22_eabi/factory/./src_rokid/include/adb_func.h:11:0,
                 from /diskdata1/yodaos/openwrt/build_dir/target-arm_cortex-a7+neon_glibc-2.22_eabi/factory/src_rokid/app/adb_factory.c:4:
/diskdata1/yodaos/openwrt/build_dir/target-arm_cortex-a7+neon_glibc-2.22_eabi/factory/./src_rokid/include/common.h:27:24: fatal error: vsp_ioctl.h: No such file or directory
compilation terminated.
```

**Comment by xqbumu** [comment]
最后改用 products/rokid/universal/configs/leo_k18_universal_node_defconfig 问题解决，

**Comment by xqbumu** [comment]
问题关闭

**Comment by yorkie** [comment]
问题应该没有解决，@Machaojoy 帮忙看一下 vsp_firmware 的问题。

**Comment by yorkie** [comment]
@Machaojoy should fixed this problem, now `leo_k18_dev33_defconfig` should work :)
