### ISSUE TITLE
error: .repo/manifests/: contains uncommitted changes

### ISSUE THREAD

**Issue by 786694836** [yodaos-project/yodaos#12]

**Comment by yorkie** [comment]
Hi @786694836 What's your command that prints the error?

**Comment by xqbumu** [comment]
在 .repo/manifests 下执行 git stash, 然后回到工作目录，执行 repo sync, 然后拉不到代码不用管，然后再回到 .repo/manifests 目录下，执行 git stash pop。
然后就正常了。
遇到如此问题，就按这个套路。

**Comment by zhangyanbo2007** [comment]
15821444815,大家可以加我微信，针对AI操作系统，交流交流

**Comment by yorkie** [comment]
The v9.x codebase has deprecated the repo tool, just one command to download the most source, please try with https://github.com/yodaos-project/yodaos#download-source.
