### ISSUE TITLE
Unable to register developer account

### ISSUE THREAD

**Issue by linonetwo** [yodaos-project/yodaos#17]
In https://github.com/yodaos-project/yodaos#download-source it recommends registering.

But the SMS verify code takes 15 min to deliver, and it keeps saying it is outdated.

So currently it is very uneasy to register.

**Comment by yorkie** [comment]
Hey, sorry about that because our gerrit server could only connect with the Rokid's open platform for now, could you please provide your phone number?

**Comment by linonetwo** [comment]
I don't want to bother you, so I tried again just now and this time it worked...

**Comment by linonetwo** [comment]
I would recommend you to set the verify code outdate time to 15-30min...
