### ISSUE TITLE
Unable to locate package libusb

### ISSUE THREAD

**Issue by hyj1991** [yodaos-project/yodaos#4]
Run `apt-get install build-essential subversion libncurses5-dev zlib1g-dev gawk gcc-multilib flex git-core gettext libssl-dev unzip texinfo device-tree-compiler dosfstools libusb`

Will get error：

* **Unable to locate package libusb**

Maybe `libusb` -> `libusb-1.0-0` ?

**Comment by yorkie** [comment]
Thank you @hyj1991, it should be `libusb-1.0-0-dev`, updated at README :)
